#!/usr/bin/env bash
# Executes the notebook, exports to reveal.js slides, and points it at the
# repo's shared assets/ (reveal.js + MathJax), then rewrites the nbconvert
# bootstrap to plain <script> tags so the deck actually initializes as a
# slideshow when opened directly (double-clicked / file://), not just when
# served over http.
#
# Unlike lecture 01's older sibling, this lecture's canonical notebook is
# hand-authored (not generated by a build_notebook.py script), so this script
# starts from "execute" rather than "build".
#
# Run from inside this lecture's folder: ./export_slides.sh
set -euo pipefail
cd "$(dirname "$0")"

NB=PSE-823_Lecture-02_Modeling-Laplace.ipynb
SLIDES=PSE-823_Lecture-02_Modeling-Laplace_slides.slides.html
COLAB=PSE-823_Lecture-02_Modeling-Laplace_colab.ipynb
ASSETS=../../assets   # shared reveal.js/ + mathjax/, relative to this lecture folder

echo "== Executing notebook =="
jupyter nbconvert --to notebook --execute --output "$NB" "$NB"

echo "== Exporting to reveal.js slides (shared repo assets) =="
jupyter nbconvert --to slides "$NB" --output "${SLIDES%.slides.html}" \
    --SlidesExporter.reveal_url_prefix="$ASSETS/reveal.js"

echo "== Localizing MathJax + removing jquery/require/mermaid =="
python3 - "$ASSETS" "$SLIDES" <<'PYEOF'
import re
import sys
assets, path = sys.argv[1], sys.argv[2]
with open(path) as f:
    html = f.read()

old = 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe'
new = f'{assets}/mathjax/MathJax.js?config=TeX-AMS_CHTML-full,Safe'
assert html.count(old) == 1, "MathJax CDN line not found / already replaced"
html = html.replace(old, new)

# jquery/require.js versions are pinned by nbconvert's template; mermaid's
# version drifts across nbconvert releases, so match it loosely.
head_pattern = re.compile(
    r'<script src="https://cdnjs\.cloudflare\.com/ajax/libs/jquery/[^"]*"></script>'
    r'<script src="https://cdnjs\.cloudflare\.com/ajax/libs/require\.js/[^"]*"></script>'
    r'<script type="module">\s*'
    r"  import mermaid from 'https://cdnjs\.cloudflare\.com/ajax/libs/mermaid/[^']*';\s*"
    r'  mermaid\.initialize\(\{ startOnLoad: true \}\);\s*'
    r'</script>'
)
html, n = head_pattern.subn('', html)
assert n == 1, "jquery/require/mermaid head block not found / already replaced"

old_bootstrap = '''<script>
require(
    {
      // it makes sense to wait a little bit when you are loading
      // reveal from a cdn in a slow connection environment
      waitSeconds: 15
    },
    [
      "REVEAL_JS_PATH/dist/reveal.js",
      "REVEAL_JS_PATH/plugin/notes/notes.js"
    ],

    function(Reveal, RevealNotes){
        // Full list of configuration options available here: https://github.com/hakimel/reveal.js#configuration
        Reveal.initialize({
            controls: true,
            progress: true,
            history: true,
            transition: "slide",
            slideNumber: "",
            plugins: [RevealNotes],
            width: 960,
			      height: 700,

        });

        var update = function(event){
          if(MathJax.Hub.getAllJax(Reveal.getCurrentSlide())){
            MathJax.Hub.Rerender(Reveal.getCurrentSlide());
          }
        };

        Reveal.addEventListener('slidechanged', update);

        function setScrollingSlide() {
            var scroll = false
            if (scroll === true) {
              var h = $('.reveal').height() * 0.95;
              $('section.present').find('section')
                .filter(function() {
                  return $(this).height() > h;
                })
                .css('height', 'calc(95vh)')
                .css('overflow-y', 'scroll')
                .css('margin-top', '20px');
            }
        }

        // check and set the scrolling slide every time the slide change
        Reveal.addEventListener('slidechanged', setScrollingSlide);
    }
);
</script>'''.replace("REVEAL_JS_PATH", assets + "/reveal.js")

new_bootstrap = f'''<script src="{assets}/reveal.js/dist/reveal.js"></script>
<script src="{assets}/reveal.js/plugin/notes/notes.js"></script>
<script>
    Reveal.initialize({{
        controls: true,
        progress: true,
        history: true,
        transition: "slide",
        slideNumber: "",
        plugins: [RevealNotes],
        width: 960,
        height: 700,
    }});

    var update = function(event){{
      if (window.MathJax && MathJax.Hub && MathJax.Hub.getAllJax(Reveal.getCurrentSlide())){{
        MathJax.Hub.Rerender(Reveal.getCurrentSlide());
      }}
    }};

    Reveal.addEventListener('slidechanged', update);
</script>'''
assert html.count(old_bootstrap) == 1, "reveal.js bootstrap block not found / already replaced"
html = html.replace(old_bootstrap, new_bootstrap)

with open(path, "w") as f:
    f.write(html)
print("Localized MathJax; removed jquery/require.js/mermaid; replaced RequireJS bootstrap with plain script tags.")
PYEOF

echo "== Injecting custom lecture theme CSS =="
python3 - "$ASSETS" "$SLIDES" <<'PYEOF'
import sys
assets, path = sys.argv[1], sys.argv[2]
with open(f"{assets}/reveal-lecture-theme.css") as f:
    css = f.read()
with open(path) as f:
    html = f.read()
assert "PSE-823 reveal.js lecture theme" not in html, "Theme already injected"
style_tag = f"\n<style>\n{css}\n</style>\n</head>"
html = html.replace("</head>", style_tag, 1)
with open(path, "w") as f:
    f.write(html)
print("Theme CSS injected.")
PYEOF

echo "== Verifying no external CDN references remain =="
if grep -qE "cdnjs\.cloudflare\.com|unpkg\.com|jsdelivr\.net|fonts\.googleapis\.com" "$SLIDES"; then
    echo "WARNING: external CDN references still present!"
    grep -nE "cdnjs\.cloudflare\.com|unpkg\.com|jsdelivr\.net|fonts\.googleapis\.com" "$SLIDES"
    exit 1
else
    echo "OK: fully self-contained, no external CDN dependencies."
fi

echo "== Generating Colab variant =="
# Same lecture with absolute image URLs + a pip-install cell, since Colab has
# neither the images/ folder nor python-control.
python3 ../../tools/make_colab.py "$NB"

echo "== Done: $SLIDES + $COLAB =="
